export const sidebar = {
  "/chapters/": [
    {
      text: "文档目录",
      items: [
        {
          text: "第1章 Elasticsearch概述",
          collapsed: false,
          items: [
            { text: "章节总览", link: "/chapters/chapter-01/" },
            { text: "01-开篇", link: "/chapters/chapter-01/01-01-开篇" },
            { text: "02-技术选型", link: "/chapters/chapter-01/02-02-技术选型" },
            { text: "03-教学大纲", link: "/chapters/chapter-01/03-03-教学大纲" },
          ],
        },
        {
          text: "第2章 Elasticsearch入门",
          collapsed: false,
          items: [
            { text: "章节总览", link: "/chapters/chapter-02/" },
            { text: "04-入门-环境准备", link: "/chapters/chapter-02/01-04-入门-环境准备" },
            { text: "05-入门-RESTful & JSON", link: "/chapters/chapter-02/02-05-入门-restful-json" },
            { text: "06-入门-Postman客户端工具", link: "/chapters/chapter-02/03-06-入门-postman客户端工具" },
            { text: "07-入门-倒排索引", link: "/chapters/chapter-02/04-07-入门-倒排索引" },
            { text: "08-入门-HTTP-索引-创建", link: "/chapters/chapter-02/05-08-入门-http-索引-创建" },
            { text: "09-入门-HTTP-索引-查询 & 删除", link: "/chapters/chapter-02/06-09-入门-http-索引-查询-删除" },
            { text: "10-入门-HTTP-文档-创建（Put & Post）", link: "/chapters/chapter-02/07-10-入门-http-文档-创建-put-post" },
            { text: "11-入门-HTTP-查询-主键查询 & 全查询", link: "/chapters/chapter-02/08-11-入门-http-查询-主键查询-全查询" },
            { text: "12-入门-HTTP-全量修改 & 局部修改 & 删除", link: "/chapters/chapter-02/09-12-入门-http-全量修改-局部修改-删除" },
            { text: "13-入门-HTTP-条件查询 & 分页查询 & 查询排序", link: "/chapters/chapter-02/10-13-入门-http-条件查询-分页查询-查询排序" },
            { text: "14-入门-HTTP-多条件查询 & 范围查询", link: "/chapters/chapter-02/11-14-入门-http-多条件查询-范围查询" },
            { text: "15-入门-HTTP-全文检索 & 完全匹配 & 高亮查询", link: "/chapters/chapter-02/12-15-入门-http-全文检索-完全匹配-高亮查询" },
            { text: "16-入门-HTTP-聚合查询", link: "/chapters/chapter-02/13-16-入门-http-聚合查询" },
            { text: "17-入门-HTTP-映射关系", link: "/chapters/chapter-02/14-17-入门-http-映射关系" },
            { text: "18-入门-JavaAPI-环境准备", link: "/chapters/chapter-02/15-18-入门-javaapi-环境准备" },
            { text: "19-入门-JavaAPI-索引-创建", link: "/chapters/chapter-02/16-19-入门-javaapi-索引-创建" },
            { text: "20-入门-JavaAPI-索引-查询 & 删除", link: "/chapters/chapter-02/17-20-入门-javaapi-索引-查询-删除" },
            { text: "21-入门-JavaAPI-文档-新增 & 修改", link: "/chapters/chapter-02/18-21-入门-javaapi-文档-新增-修改" },
            { text: "22-入门-JavaAPI-文档-查询 & 删除", link: "/chapters/chapter-02/19-22-入门-javaapi-文档-查询-删除" },
            { text: "23-入门-JavaAPI-文档-批量新增 & 批量删除", link: "/chapters/chapter-02/20-23-入门-javaapi-文档-批量新增-批量删除" },
            { text: "24-入门-JavaAPI-文档-高级查询-全量查询", link: "/chapters/chapter-02/21-24-入门-javaapi-文档-高级查询-全量查询" },
            { text: "25-入门-JavaAPI-文档-高级查询-分页查询 & 条件查询 & 查询排序", link: "/chapters/chapter-02/22-25-入门-javaapi-文档-高级查询-分页查询-条件查询-查询排序" },
            { text: "26-入门-JavaAPI-文档-高级查询-组合查询 & 范围查询", link: "/chapters/chapter-02/23-26-入门-javaapi-文档-高级查询-组合查询-范围查询" },
            { text: "27-入门-JavaAPI-文档-高级查询-模糊查询 & 高亮查询", link: "/chapters/chapter-02/24-27-入门-javaapi-文档-高级查询-模糊查询-高亮查询" },
            { text: "28-入门-JavaAPI-文档-高级查询-最大值查询 & 分组查询", link: "/chapters/chapter-02/25-28-入门-javaapi-文档-高级查询-最大值查询-分组查询" },
          ],
        },
        {
          text: "第3章 Elasticsearch环境",
          collapsed: false,
          items: [
            { text: "章节总览", link: "/chapters/chapter-03/" },
            { text: "29-环境-简介", link: "/chapters/chapter-03/01-29-环境-简介" },
            { text: "30-环境-Windows集群部署", link: "/chapters/chapter-03/02-30-环境-windows集群部署" },
            { text: "31-环境-Linux单节点部署", link: "/chapters/chapter-03/03-31-环境-linux单节点部署" },
            { text: "32-环境-Linux集群部署", link: "/chapters/chapter-03/04-32-环境-linux集群部署" },
          ],
        },
        {
          text: "第4章 Elasticsearch进阶",
          collapsed: false,
          items: [
            { text: "章节总览", link: "/chapters/chapter-04/" },
            { text: "33-进阶-核心概念", link: "/chapters/chapter-04/01-33-进阶-核心概念" },
            { text: "34-进阶-系统架构-简介", link: "/chapters/chapter-04/02-34-进阶-系统架构-简介" },
            { text: "35-进阶-单节点集群", link: "/chapters/chapter-04/03-35-进阶-单节点集群" },
            { text: "36-进阶-故障转移", link: "/chapters/chapter-04/04-36-进阶-故障转移" },
            { text: "37-进阶-水平扩容", link: "/chapters/chapter-04/05-37-进阶-水平扩容" },
            { text: "38-进阶-应对故障", link: "/chapters/chapter-04/06-38-进阶-应对故障" },
            { text: "39-进阶-路由计算 & 分片控制", link: "/chapters/chapter-04/07-39-进阶-路由计算-分片控制" },
            { text: "40-进阶-数据写流程", link: "/chapters/chapter-04/08-40-进阶-数据写流程" },
            { text: "41-进阶-数据读流程", link: "/chapters/chapter-04/09-41-进阶-数据读流程" },
            { text: "42-进阶-更新流程 & 批量操作流程", link: "/chapters/chapter-04/10-42-进阶-更新流程-批量操作流程" },
            { text: "43-进阶-倒排索引", link: "/chapters/chapter-04/11-43-进阶-倒排索引" },
            { text: "44-进阶-文档搜索", link: "/chapters/chapter-04/12-44-进阶-文档搜索" },
            { text: "45-进阶-文档刷新 & 文档刷写 & 文档合并", link: "/chapters/chapter-04/13-45-进阶-文档刷新-文档刷写-文档合并" },
            { text: "46-进阶-文档分析", link: "/chapters/chapter-04/14-46-进阶-文档分析" },
            { text: "47-进阶-文档控制", link: "/chapters/chapter-04/15-47-进阶-文档控制" },
            { text: "48-进阶-文档展示-Kibana", link: "/chapters/chapter-04/16-48-进阶-文档展示-kibana" },
          ],
        },
        {
          text: "第5章 Elasticsearch集成",
          collapsed: false,
          items: [
            { text: "章节总览", link: "/chapters/chapter-05/" },
            { text: "49-框架集成-SpringData-整体介绍", link: "/chapters/chapter-05/01-49-框架集成-springdata-整体介绍" },
            { text: "50-框架集成-SpringData-代码功能集成", link: "/chapters/chapter-05/02-50-框架集成-springdata-代码功能集成" },
            { text: "51-框架集成-SpringData-集成测试-索引操作", link: "/chapters/chapter-05/03-51-框架集成-springdata-集成测试-索引操作" },
            { text: "52-框架集成-SpringData-集成测试-文档操作", link: "/chapters/chapter-05/04-52-框架集成-springdata-集成测试-文档操作" },
            { text: "53-框架集成-SpringData-集成测试-文档搜索", link: "/chapters/chapter-05/05-53-框架集成-springdata-集成测试-文档搜索" },
            { text: "54-框架集成-SparkStreaming-集成", link: "/chapters/chapter-05/06-54-框架集成-sparkstreaming-集成" },
            { text: "55-框架集成-Flink-集成", link: "/chapters/chapter-05/07-55-框架集成-flink-集成" },
          ],
        },
        {
          text: "第6章 Elasticsearch优化",
          collapsed: false,
          items: [
            { text: "章节总览", link: "/chapters/chapter-06/" },
            { text: "56-优化-硬件选择", link: "/chapters/chapter-06/01-56-优化-硬件选择" },
            { text: "57-优化-分片策略", link: "/chapters/chapter-06/02-57-优化-分片策略" },
            { text: "58-优化-路由选择", link: "/chapters/chapter-06/03-58-优化-路由选择" },
            { text: "59-优化-写入速度优化", link: "/chapters/chapter-06/04-59-优化-写入速度优化" },
            { text: "60-优化-内存设置", link: "/chapters/chapter-06/05-60-优化-内存设置" },
            { text: "61-优化-重要配置", link: "/chapters/chapter-06/06-61-优化-重要配置" },
          ],
        },
        {
          text: "第7章 Elasticsearch面试题",
          collapsed: false,
          items: [
            { text: "章节总览", link: "/chapters/chapter-07/" },
            { text: "62-面试题", link: "/chapters/chapter-07/01-62-面试题" },
          ],
        },
      ],
    },
  ],
};
